apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: auth-check-
spec:
  serviceAccountName: tek-wli
  taskRef:
    name: gcloud
  params:
  - name: ARGS
    value: ['auth', 'list']
