apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-pr
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: github-listener
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-interceptor-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["pull_request"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['closed']"
      bindings:
        - ref: github-pr-binding
      template:
        ref: github-pr-pipeline-template
#    - name: github-listener-new
#      interceptors:
#        - ref:
#            name: "github"
#          params:
#            - name: "secretRef"
#              value:
#                secretName: github-interceptor-secret
#                secretKey: secretToken
#            - name: "eventTypes"
#              value: ["pull_request"]
#        - ref:
#            name: "cel"
#          params:
#            - name: "filter"
#              value: "body.action in ['closed']"
#      bindings:
#        - ref: github-pr-binding-new
#      template:
#        ref: github-pr-pipeline-template-test 
